# Generated by Django 4.1.4 on 2022-12-18 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_alter_medicine_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='created_date',
        ),
    ]
